// File: D:\jonathan\Documents\MATLAB\Examples\ucie_sim_c_build\ucie_sim_c_dpi.sv
// Created: 2025-03-13 13:32:18
// Generated by MATLAB 24.2 and HDL Verifier 24.2

`timescale 1ns / 1ns

import ucie_sim_c_dpi_pkg::*;

interface vif_t;
bit clk;
bit clk_enable;
bit reset;

/* Simulink signal name: 'Inport' */
 real Inport ;

/* Simulink signal name: 'Outport' */
 real Outport ;

endinterface

module ucie_sim_c_dpi(
    vif_t vif
);

    chandle objhandle=null;

    initial begin
        objhandle = DPI_ucie_sim_c_initialize(objhandle);
    end

    final begin
        DPI_ucie_sim_c_terminate(objhandle);
    end

    always @(posedge vif.clk or posedge vif.reset) begin
        if(vif.reset== 1'b1) begin
            objhandle=DPI_ucie_sim_c_reset(objhandle,
            vif.Inport, vif.Outport);
            //Run-time error reporting
            SV_ucie_sim_c_reportErrMsg(objhandle);
        end
        else if(vif.clk_enable) begin
            DPI_ucie_sim_c_output(objhandle,
            vif.Inport, vif.Outport);
            DPI_ucie_sim_c_update(objhandle,
            vif.Inport);
            //Run-time error reporting
            SV_ucie_sim_c_reportErrMsg(objhandle);
        end
    end
endmodule
