/*

 File: D:\jonathan\Documents\MATLAB\Examples\ucie_sim_c_build\ucie_sim_c_dpi.h
 Created: 2025-03-13 13:32:14
 Generated by MATLAB 24.2 and HDL Verifier 24.2

*/

#ifndef RTW_HEADER_ucie_sim_c_dpi_h_
#define RTW_HEADER_ucie_sim_c_dpi_h_

#ifdef __cplusplus
#define DPI_LINK_DECL extern "C"
#else
#define DPI_LINK_DECL
#endif

#ifndef DPI_DLL_EXPORT
#if defined(_MSC_VER) || defined(__LCC__)
#define DPI_DLL_EXPORT __declspec(dllexport)
#else
#define DPI_DLL_EXPORT 
#endif
#endif






DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_ucie_sim_c_initialize(void* existhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_ucie_sim_c_reset_f(void* objhandle, real_T Inport, real_T* Outport);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_output_f(void* objhandle, real_T Inport, real_T* Outport);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_update_f(void* objhandle, real_T Inport);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_terminate(void* objhandle);
DPI_LINK_DECL DPI_DLL_EXPORT char_T* DPI_ucie_sim_c_getErrMsg(void* objhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_DFEClkFwdParameter_f(void* objhandle,real_T RTWStructParam_DFEClkFwdParameter_ForwardClockOffset, real_T RTWStructParam_DFEClkFwdParameter_Mode, real_T RTWStructParam_DFEClkFwdParameter_ReferenceOffset, real_T RTWStructParam_DFEClkFwdParameter_PhaseOffset, void * RTWStructParam_DFEClkFwdParameter_TapWeights);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_FFEParameter_f(void* objhandle,real_T RTWStructParam_FFEParameter_Mode, void * RTWStructParam_FFEParameter_TapWeights, real_T RTWStructParam_FFEParameter_ConfigSelect);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_CTLEParameter_f(void* objhandle,real_T RTWStructParam_CTLEParameter_Mode, real_T RTWStructParam_CTLEParameter_ConfigSelect, real_T RTWStructParam_CTLEParameter_SliceSelect);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_VGAParameter_f(void* objhandle,real_T RTWStructParam_VGAParameter_Gain, real_T RTWStructParam_VGAParameter_Mode);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_Aggressors_f(void* objhandle,real_T RTWStructParam_Aggressors);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_ChannelImpulse_f(void* objhandle,void * RTWStructParam_ChannelImpulse);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_Modulation_f(void* objhandle,real_T RTWStructParam_Modulation);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_RowSize_f(void* objhandle,real_T RTWStructParam_RowSize);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_SampleInterval_f(void* objhandle,real_T RTWStructParam_SampleInterval);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_ucie_sim_c_setparam_SymbolTime_f(void* objhandle,real_T RTWStructParam_SymbolTime);

#endif /*RTW_HEADER_ucie_sim_c_dpi_h_*/

