# Description: DO file for simulating generated test bench ucie_sim_c_dpi_tb with Siemens Questa/ModelSim 
# File: D:\jonathan\Documents\MATLAB\Examples\ucie_sim_c_build\dpi_tb\run_tb_mq.do
# Created: 2025-03-13 13:32:41
# Generated by MATLAB 24.2 and HDL Verifier 24.2

# Using plusarg to determine coverage count for verify() PASS
# result.  If filtered, NO covergroup is created. 
# Examples:
#   NO PLUSARG          : at_least=1 (default value)
#   +my_model:33:8      : FILTER -- DO NOT COVER (backward compatible behavior)
#   +my_model:33:8=0    : FILTER (alternative form)
#   +my_model:33:8=-1   : FILTER (alternative form)
#   +my_model:33:8=13   : at_least=13

# Using plusarg to get an INFO message for every unfiltered verify()
# result.
#   +VERBOSE_VERIFY


if { [info exists ::env(LAUNCH_SIMULATOR_GUI_MODE)] && [string length $::env(LAUNCH_SIMULATOR_GUI_MODE)] != 0} { 
	 set final_cmd {puts "Execute run -all to start testbench simulation"} 
} else { 
	 set final_cmd {run -all} 
}
# Arbitrary compilation arguments can be placed in $(EXTRA_SVDPI_COMP_ARGS) environment variable
if { [info exists ::env(EXTRA_SVDPI_COMP_ARGS)] } {
    set EXTRA_SVDPI_COMP_ARGS $env(EXTRA_SVDPI_COMP_ARGS)
} else {
    set EXTRA_SVDPI_COMP_ARGS ""
}
# Arbitrary simulation arguments can be placed in $(EXTRA_SVDPI_SIM_ARGS) environment variable
if { [info exists ::env(EXTRA_SVDPI_SIM_ARGS)] } {
    set EXTRA_SVDPI_SIM_ARGS $env(EXTRA_SVDPI_SIM_ARGS)
} else {
    set EXTRA_SVDPI_SIM_ARGS ""
}


vlib work
eval vlog +define+MG_SIM ./ucie_sim_c_dpi_pkg.sv ./ucie_sim_c_dpi.sv ./ucie_sim_c_dpi_tb.sv $EXTRA_SVDPI_COMP_ARGS
eval vsim $EXTRA_SVDPI_SIM_ARGS +define+MG_SIM -c -voptargs=+acc work.ucie_sim_c_dpi_tb -L ./work
add wave /ucie_sim_c_dpi_tb/vif/clk
add wave /ucie_sim_c_dpi_tb/vif/clk_enable
add wave /ucie_sim_c_dpi_tb/vif/reset
add wave /ucie_sim_c_dpi_tb/vif/Inport
add wave /ucie_sim_c_dpi_tb/vif/Outport
add wave /ucie_sim_c_dpi_tb/Outport_ref
eval $final_cmd
