// File: D:\jonathan\Documents\MATLAB\Examples\ucie_sim_c_build\dpi_tb\ucie_sim_c_dpi_tb.sv
// Created: 2025-03-13 13:32:29
// Generated by MATLAB 24.2 and HDL Verifier 24.2

`timescale 1ns / 1ns

import ucie_sim_c_dpi_pkg::*;

module ucie_sim_c_dpi_tb;
    vif_t vif();
    
    real Outport_ref;
    real Outport_read;
    
    // File Handles
    integer fid_Inport;
    integer fid_Outport;
    // Other test bench variables
    integer fscanf_status;
    reg testFailure;
    integer vecCompareCount;
    reg tbDone;
    bit[63:0] real_bit64;
    bit[31:0] shortreal_bit64;
    parameter CLOCK_PERIOD= 10;
    parameter TOLERANCE= 4.440892098500626e-16;
    parameter CLOCK_HOLD= 2;
    parameter RESET_LEN= 2*CLOCK_PERIOD+CLOCK_HOLD;
    // Initialize variables
    initial begin
        vif.clk = 1;
        vif.clk_enable = 0;
        vif.reset = 1;
        testFailure = 0;
        vecCompareCount = 0;
        tbDone = 0;
        $display("Tolerance parameter for floating point comparisons is set to: %e.\nOverride the SystemVerilog parameter using the EXTRA_SVDPI_SIM_ARGS or EXTRA_SVDPI_COMP_ARGS appropriate for your simulator.", TOLERANCE);
        fid_Inport = $fopen("dpig_in1.dat","r");
        fscanf_status = $fscanf(fid_Inport, "%h", real_bit64);
        vif.Inport = $bitstoreal(real_bit64);
        fscanf_status = $rewind(fid_Inport);
        fid_Outport = $fopen("dpig_out1.dat","r");
        #RESET_LEN vif.reset = 0;
    end
    // Clock
    always #(CLOCK_PERIOD/2) vif.clk = ~ vif.clk;
    always@(posedge vif.clk) begin
        if (vif.reset == 0 && tbDone == 0) begin
            #CLOCK_HOLD
            vif.clk_enable <= 1;
            fscanf_status = $fscanf(fid_Inport, "%h", real_bit64);
            vif.Inport = $bitstoreal(real_bit64);
            if ($feof(fid_Inport)) 
                tbDone = 1;
            fscanf_status = $fscanf(fid_Outport, "%h", real_bit64);
            Outport_read = $bitstoreal(real_bit64);
            if ($feof(fid_Outport)) 
                tbDone = 1;
            Outport_ref <= Outport_read;
            if (vif.clk_enable == 1) begin
                vecCompareCount = vecCompareCount + 1;
                assert ( ((Outport_ref - vif.Outport) <= TOLERANCE) && ((Outport_ref - vif.Outport) >= -1*TOLERANCE) ) else begin
                    testFailure = 1;
                    $display("ERROR in output Outport_ref at time %0t :", $time);
                    $display("Expected %e; Actual %e; Difference %e", Outport_ref, vif.Outport, Outport_ref-vif.Outport);
                end
                if (tbDone == 1) begin
                    if (testFailure == 0) 
                        $display("**************TEST COMPLETED (PASSED)**************");
                    else
                        $display("**************TEST COMPLETED (FAILED)**************");
                    $finish;
                end
            end
            if (tbDone)
                vif.clk_enable <= 0;
        end
    end

    final begin
        $display("Vector compare count = %0d", vecCompareCount);
    end

    // Instantiate DUT
    ucie_sim_c_dpi u_ucie_sim_c_dpi(
    .vif(vif)
    );
endmodule
